/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Zuajj
 */
public class frmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmAdmin
     */
    public frmAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        //evita cerrar Fondo con ALT+C
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        try{
          this.setIconImage(new ImageIcon(getClass().getResource("icono.png")).getImage());
        
        }catch(Exception e){} 
    }
    public static boolean categoria=false;
    public static boolean ControlProducto=false;
    public static boolean empleado=false;
    public static boolean cliente=false;
    public static boolean proveedor=false;
    public static boolean reportes=false;
    public static boolean respaldo=false;
    public static boolean listaEmpleado=false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        opcionEmpleado = new javax.swing.JMenuItem();
        opcionCliente = new javax.swing.JMenuItem();
        opcionProveedor = new javax.swing.JMenuItem();
        opcionReportes = new javax.swing.JMenuItem();
        opcionRespaldo = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        opcionSalir = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        opcionControlProductos = new javax.swing.JMenuItem();
        opcionCategorias = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();
        opcionAyudaRemota = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador SiFa");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        menuAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1444000003_printer.png"))); // NOI18N
        menuAdministracion.setText("Administración");

        opcionEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        opcionEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1443999664_unknown.png"))); // NOI18N
        opcionEmpleado.setText("Empleado");
        opcionEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEmpleadoActionPerformed(evt);
            }
        });
        menuAdministracion.add(opcionEmpleado);

        opcionCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        opcionCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1443999695_matureman1.png"))); // NOI18N
        opcionCliente.setText("Cliente");
        opcionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionClienteActionPerformed(evt);
            }
        });
        menuAdministracion.add(opcionCliente);

        opcionProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        opcionProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1443999723_malecostume.png"))); // NOI18N
        opcionProveedor.setText("Proveedor");
        opcionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionProveedorActionPerformed(evt);
            }
        });
        menuAdministracion.add(opcionProveedor);

        opcionReportes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        opcionReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1443999850_Report.png"))); // NOI18N
        opcionReportes.setText("Reportes");
        opcionReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionReportesActionPerformed(evt);
            }
        });
        menuAdministracion.add(opcionReportes);

        opcionRespaldo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        opcionRespaldo.setText("Respaldo");
        opcionRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionRespaldoActionPerformed(evt);
            }
        });
        menuAdministracion.add(opcionRespaldo);
        menuAdministracion.add(separador);

        opcionSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        opcionSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1443999924_Close.png"))); // NOI18N
        opcionSalir.setText("Salir");
        opcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSalirActionPerformed(evt);
            }
        });
        menuAdministracion.add(opcionSalir);

        menuPrincipal.add(menuAdministracion);

        menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1443999965_box.png"))); // NOI18N
        menuProductos.setText("Productos");

        opcionControlProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        opcionControlProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1444000091_bill.png"))); // NOI18N
        opcionControlProductos.setText("Control Productos");
        opcionControlProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionControlProductosActionPerformed(evt);
            }
        });
        menuProductos.add(opcionControlProductos);

        opcionCategorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        opcionCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1444000134_categories.png"))); // NOI18N
        opcionCategorias.setText("Categorias");
        opcionCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCategoriasActionPerformed(evt);
            }
        });
        menuProductos.add(opcionCategorias);

        menuPrincipal.add(menuProductos);

        jMenu2.setText("Ventas");
        menuPrincipal.add(jMenu2);

        jMenu1.setText("Configuración");
        menuPrincipal.add(jMenu1);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1444000039_info.png"))); // NOI18N
        menuAyuda.setText("Ayuda");

        opcionAyudaRemota.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        opcionAyudaRemota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1443999741_supportmale.png"))); // NOI18N
        opcionAyudaRemota.setText("Ayuda Remota");
        opcionAyudaRemota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAyudaRemotaActionPerformed(evt);
            }
        });
        menuAyuda.add(opcionAyudaRemota);

        menuPrincipal.add(menuAyuda);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_opcionSalirActionPerformed

    private void opcionAyudaRemotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAyudaRemotaActionPerformed
        // TODO add your handling code here:
        getToolkit().beep();
        JOptionPane.showMessageDialog(rootPane, "Cominicate con nosotros:"+"\n"+
                "22-91-16-46-13","Ayuda Remota",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_opcionAyudaRemotaActionPerformed

    private void opcionCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCategoriasActionPerformed
        // TODO add your handling code here:
        frmCategorias a = new frmCategorias();
        int y = (escritorio.getHeight()/2)-a.getHeight()/2;
        int x = (escritorio.getWidth()/2)-a.getWidth()/2;
        if(categoria==false){
            escritorio.add(a);
            a.setLocation(x, y);
            a.show();
            categoria=true;
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "La ventana esta en uso","Erro de Ventana",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_opcionCategoriasActionPerformed

    private void opcionControlProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionControlProductosActionPerformed
        // TODO add your handling code here:
        frmControlProductos a = new frmControlProductos();
        int y = (escritorio.getHeight()/2)-a.getHeight()/2;
        int x = (escritorio.getWidth()/2)-a.getWidth()/2;
        if(ControlProducto==false){
            escritorio.add(a);
            a.setLocation(x, y);
            a.show();
            ControlProducto=true;
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "La ventana esta en uso","Erro de Ventana",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_opcionControlProductosActionPerformed

    private void opcionEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEmpleadoActionPerformed
        // TODO add your handling code here:
        frmListaEmpleado a = new frmListaEmpleado();
        int y = (escritorio.getHeight()/2)-a.getHeight()/2;
        int x = (escritorio.getWidth()/2)-a.getWidth()/2;
        if(listaEmpleado==false){
            this.escritorio.add(a);
            a.setLocation(x, y);
            a.show();
            
            //Permite que la ventana no se abra dos veces, se desactiva para las listas
            listaEmpleado=true;
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "La ventana esta en uso","Erro de Ventana",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_opcionEmpleadoActionPerformed

    private void opcionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionClienteActionPerformed
        // TODO add your handling code here:
        frmCliente a = new frmCliente();
        int y = (escritorio.getHeight()/2)-a.getHeight()/2;
        int x = (escritorio.getWidth()/2)-a.getWidth()/2;
        if(cliente==false){
            escritorio.add(a);
            a.setLocation(x, y);
            a.show();
            cliente=true;
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "La ventana esta en uso","Erro de Ventana",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_opcionClienteActionPerformed

    private void opcionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionProveedorActionPerformed
        // TODO add your handling code here:
        frmProveedor a = new frmProveedor();
        int y = (escritorio.getHeight()/2)-a.getHeight()/2;
        int x = (escritorio.getWidth()/2)-a.getWidth()/2;
        if(proveedor==false){
            escritorio.add(a);
            a.setLocation(x, y);
            a.show();
            proveedor=true;
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "La ventana esta en uso","Erro de Ventana",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_opcionProveedorActionPerformed

    private void opcionReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionReportesActionPerformed
        // TODO add your handling code here:
        frmReportes a = new frmReportes();
        int y = (escritorio.getHeight()/2)-a.getHeight()/2;
        int x = (escritorio.getWidth()/2)-a.getWidth()/2;
        if(reportes==false){
            escritorio.add(a);
            a.setLocation(x, y);
            a.show();
            reportes=true;
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "La ventana esta en uso","Erro de Ventana",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_opcionReportesActionPerformed

    private void opcionRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionRespaldoActionPerformed
        // TODO add your handling code here:
        frmRespaldo a = new frmRespaldo();
        int y = (escritorio.getHeight()/2)-a.getHeight()/2;
        int x = (escritorio.getWidth()/2)-a.getWidth()/2;
        if(respaldo==false){
            escritorio.add(a);
            a.setLocation(x, y);
            a.show();
            respaldo=true;
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "La ventana esta en uso","Erro de Ventana",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_opcionRespaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenuItem opcionAyudaRemota;
    private javax.swing.JMenuItem opcionCategorias;
    private javax.swing.JMenuItem opcionCliente;
    private javax.swing.JMenuItem opcionControlProductos;
    private javax.swing.JMenuItem opcionEmpleado;
    private javax.swing.JMenuItem opcionProveedor;
    private javax.swing.JMenuItem opcionReportes;
    private javax.swing.JMenuItem opcionRespaldo;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the escritorio
     */
    public javax.swing.JDesktopPane getEscritorio() {
        return escritorio;
    }

    /**
     * @param escritorio the escritorio to set
     */
    public void setEscritorio(javax.swing.JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }
}
